# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treeman < Formula
  desc "Git worktree management CLI"
  homepage "https://github.com/shoutcape/TreeMan"
  version "0.3.47"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shoutcape/TreeMan/releases/download/v0.3.47/treeman_darwin_amd64.tar.gz"
      sha256 "a5e6948bb024ddde6dda12e9c8231752cc7bba225ad356a24865b3c7b641dcc0"

      def install
        bin.install "treeman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shoutcape/TreeMan/releases/download/v0.3.47/treeman_darwin_arm64.tar.gz"
      sha256 "90abce0c11a635e5afe7ac64b5957e2e12a419a068c720dbcd913c97e3ec3394"

      def install
        bin.install "treeman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shoutcape/TreeMan/releases/download/v0.3.47/treeman_linux_amd64.tar.gz"
      sha256 "e7053833c4832af429bba43054f4982b4d4b0b608729c765d5ca041f40ed3bd3"
      def install
        bin.install "treeman"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shoutcape/TreeMan/releases/download/v0.3.47/treeman_linux_arm64.tar.gz"
      sha256 "a7051ac7747e8e6a96a8b74239db0f271f79c954d37b37dcda0e317fbfef8ad0"
      def install
        bin.install "treeman"
      end
    end
  end

  test do
    system bin/"treeman", "version"
  end
end
